### ISSUE TITLE
Chinese notice and untranslated phrases

### ISSUE THREAD

**Issue by Tehiro** [lincanbin/Carbon-Forum#11]
I upload image.
![2015-01-06 20_53_56-temart - carbon forum](https://cloud.githubusercontent.com/assets/4751246/5635102/2e787dec-95e6-11e4-81e6-b3bb95d2b206.png)

**Comment by lincanbin** [comment]
Thanks informed. 
```/static/js/global.js``` Line51

**Comment by Tehiro** [comment]
Add this to language files.

**Comment by lincanbin** [comment]
This is a must.

**Comment by Tehiro** [comment]
Ok. Maybe support for translations? global_en.js etc. ?

**Comment by lincanbin** [comment]
/static/editor/lang/en/en.js

/language/en/*.php

**Comment by lincanbin** [comment]
And Line6 in config.php.

**Comment by lincanbin** [comment]
i18n #84
