### ISSUE TITLE
web.config覆盖虚拟主机设置

### ISSUE THREAD

**Issue by imDusk** [lincanbin/Carbon-Forum#120]
用的是AppNode面板，上传完后导致所有虚拟主机的设置都出错，应该是这个文件和面板的配置文件重复了

然而这个面板搞了半天也没弄明白，最后还是弃了

不过还是建议把所有配置放到config文件夹

**Comment by lincanbin** [comment]
IIS的web.config等等文件本来就是要求在根目录生效的，不放在根目录就无效。
至于你的AppNode，是Linux环境吧，直接删除web.config即可。

这个面板开发者不及格啊，竟然会让一个主机中的配置文件影响所有主机……

**Comment by imDusk** [comment]
是啊，Nginx配置文件在哪都不说，其他主机下也没有看到生成有这个文件，为什么会影响也是莫名其妙，在hostloc看到这家公司之前做过一个跑路了，被人评论“国人公司就这样，赚钱了就跑，没钱了就回来骗”

**Comment by lincanbin** [comment]
Nginx在Nginx的程序目录里可以找到呀。
不要用那些什么面板了，直接操作Linux不好么？

**Comment by imDusk** [comment]
刚开始接触环境搭建的时候没有任何基础，自己弄了好长时间还是各种问题，遇到面板就当作一键包用来着，总感觉人家专门做这个的可能在配置上优化一些
最近接触 java web，直接yum install tomcat简直感动

**Comment by lincanbin** [comment]
没基础就顺便学一下，花不了多少时间的。
你要是一直用傻瓜面板，自己没提升，还会踩很多坑。

**Comment by imDusk** [comment]
是啊，正打算系统地学一下，谢谢
