### ISSUE TITLE
在「关注的话题」页，即使无需翻页也可以点翻页按钮翻页

### ISSUE THREAD

**Issue by hjiang** [lincanbin/Carbon-Forum#122]
<img width="695" alt="_-_carbon_forum" src="https://cloud.githubusercontent.com/assets/18527/12241456/49b867aa-b8ce-11e5-9ddc-c154621b3510.png">

然后就会显示一个空白页。

<img width="689" alt="_page2_-_carbon_forum" src="https://cloud.githubusercontent.com/assets/18527/12241479/62530504-b8ce-11e5-97af-0a25d69197c0.png">

**Comment by lincanbin** [comment]
事情是这样的，从数据库读出来的数据，是不知道它有多少的。
如果去统计它的数量，会消耗大量资源，所以我没统计关注的话题里会有多少个帖，精确分页也无从谈起。

以后或许会改为滚动加载，这样就不会有这个问题了。

**Comment by hjiang** [comment]
可以取 topics 的时候取 `limit+1` 个，实际显示 `limit` 个，就知道有没有下一页了。

其实在同一个 select 里把 count(ID) 取回来应该资源也还好吧，有 index。（我好久没写 SQL 了，不确定）

**Comment by lincanbin** [comment]
以后做成微博那样的滚动加载就好了。
