### ISSUE TITLE
移动版的菜单改进

### ISSUE THREAD

**Issue by Hanccc** [lincanbin/Carbon-Forum#136]
测试了一下移动版本，点击菜单弹出菜单后，点击菜单外位置并没有关闭菜单而是点进去帖子里面，菜单还在，这个应该要改进一下吧

**Comment by lincanbin** [comment]
菜单是滑动的，操作逻辑本来就是如此。

**Comment by Hanccc** [comment]
我觉得应该加上JS让它点击空白地方就关闭菜单，在用户体验的角度

**Comment by lincanbin** [comment]
事情是这样的，我是想说这是个Feature，不是bug。
事后我会悄悄修复的，你就不能给我个台阶下吗？

**Comment by Hanccc** [comment]
好的，不好意思打扰了。。。
