### ISSUE TITLE
能不能集成百度编辑器UEditor？

### ISSUE THREAD

**Issue by iVanilla** [lincanbin/Carbon-Forum#139]
首先我用HHVM跑了这个论坛程序一切OK。
然后我希望能用上百度编辑器UEditor，请问应该怎样修改代码，或者你们以后会把UEditor集成进去？

**Comment by lincanbin** [comment]
你没发现现在这个，就是UEditor吗？

**Comment by iVanilla** [comment]
@lincanbin 没注意到，我是看了你在知乎上面的回答才决定用这个论坛的，上面的截图貌似是CKEditor

**Comment by lincanbin** [comment]
UEditor，我之前调研过，算是功能最全面的编辑器了。
怎么可能不用。

**Comment by iVanilla** [comment]
@lincanbin 我在论坛提建议了，去论坛说吧
