### ISSUE TITLE
LogOut()设置Cookie是否有误

### ISSUE THREAD

**Issue by StoneMoe** [lincanbin/Carbon-Forum#155]
https://github.com/lincanbin/Carbon-Forum/blob/master/common.php#L446

CurUserExpirationTime 是不是应该改为 UserExpirationTime

**Comment by lincanbin** [comment]
你说得对，是我的错了，看来真该请个萌妹子帮我想变量名了。
Cookie名我都记串了，好在对功能也没有任何影响。

**Comment by lincanbin** [comment]
已修复，感谢反馈！
