### ISSUE TITLE
请问对于Apache的URL重写是如何实现的？

### ISSUE THREAD

**Issue by WuHuaJi0** [lincanbin/Carbon-Forum#157]
看了项目里的文件，对于nginx，有nginx.conf 实现URL重写；
对于IIS，有httpd.ini实现重写；

但是对于Apache没有看到相关的URL重写配置。
不知道是不是我理解错了，对于Apache，不是应该由.htaccess文件来实现URL重写吗？

**Comment by lincanbin** [comment]
你安装完了，就有了，没安装当然没有。

**Comment by WuHuaJi0** [comment]
原来如此 :+1:
