### ISSUE TITLE
Can't Load the preview on #'s replies 

### ISSUE THREAD

**Issue by robotrono** [lincanbin/Carbon-Forum#161]
This is normal? http://i.imgur.com/pFBC7W1.png
![pfbc7w1](https://cloud.githubusercontent.com/assets/5785188/15173598/8ea4d838-178f-11e6-88f0-11238b79dede.png)

**Comment by lincanbin** [comment]
Grab the web request and take a screenshot.

**Comment by robotrono** [comment]
Can you tell me how I do that? "Grab the web request "

**Comment by lincanbin** [comment]
Press F12 to open Developer Tools and click "Network" in your browser.

**Comment by robotrono** [comment]
Done @lincanbin http://i.imgur.com/NdEREHc.png

**Comment by lincanbin** [comment]
https://github.com/lincanbin/Carbon-Forum/commit/1cdee85b2b8c695cf4f64fe0c562483a6d3c3407

Fixed.

**Comment by lincanbin** [comment]
Thank you for your feedback. 
Cover the old json.php with the latest json.php file will be able to fix this bug.

**Comment by robotrono** [comment]
Thanks so much!

**Comment by robotrono** [comment]
@lincanbin Questions:

1. How can I access to the api?

2. Is it possible, add the connection with Facebook for register?

**Comment by lincanbin** [comment]
1. https://github.com/lincanbin/Carbon-Forum-API-Documentation
2. This feature will be added in later versions.

**Comment by robotrono** [comment]
@lincanbin I dont understand how to authenticate to my api, for the default api secret and api key are: 

$APISignature = array();
$APISignature['12450'] = 'b40484df0ad979d8ba7708d24c301c38';

What is the parameter where is the SValue?

http://api.localhost/carbon/page/1?SValue=b40484df0ad979d8ba7708d24c301c38

I get: 

{
    "Status": 0,
    "ErrorCode": 403,
    "ErrorMessage": "Forbidden"
}

**Comment by lincanbin** [comment]
# API Authentication Parameters

### Preparation
You need to set up a pair of corresponding Key and Secret in ```config.php``` like this:
```php
<?php
/*
………………………………………………………………………………………………………………………………………………………………
………………………………………………………………………………………………………………………………………………………………
…………………………………………………………Other code…………………………………………………………………………
………………………………………………………………………………………………………………………………………………………………
………………………………………………………………………………………………………………………………………………………………
*/
// API checking data
// List<Map<String APIKey, String APISecret>>
// Free to modify
$APISignature = array();
$APISignature[12450] = 'b40484df0ad979d8ba7708d24c301c38';//For Android
```

###  Parameters
Key|Value Type|Description|Obligatory|Example
---|---|---|---|---
SKey|Integer|SKey=APIKey, you can find APIKey and APISecret in ```config.php```|√|12450
STime|Integer(10)|Unix Timestamp|√|1447253145
SValue|String(32)|md5(SKey:APISecret:STime)|√|89809a5201b04c608ffa50d63892a2ca
```java
// Example
String SValue = md5("12450" + "b40484df0ad979d8ba7708d24c301c38" + "1447253145");
//SValue = "89809a5201b04c608ffa50d63892a2ca";
```

**Comment by robotrono** [comment]
api.url.com/carbon/page/1?SValue=89809a5201b04c608ffa50d63892a2ca 

Can't get the data

**Comment by lincanbin** [comment]
Time must be the current unix timestamp.

**Comment by alwaysontop617** [comment]
Wow!! :D
