### ISSUE TITLE
Support for Web Parakeet

### ISSUE THREAD

**Issue by alwaysontop617** [lincanbin/Carbon-Forum#165]
https://github.com/WebParakeet

Adding Support for Web Parakeet

**Comment by alwaysontop617** [comment]
@lincanbin Added you to organization https://github.com/WebParakeet

**Comment by lincanbin** [comment]
What's that?

**Comment by alwaysontop617** [comment]
A hosting control panel.

**Comment by alwaysontop617** [comment]
@lincanbin This system is similar to cpanel, webmin, or kloxo. I want to add your script to our script installer.

**Comment by alwaysontop617** [comment]
#166

**Comment by alwaysontop617** [comment]
#167

**Comment by alwaysontop617** [comment]
Can you please join my organization?

**Comment by alwaysontop617** [comment]
#168
