### ISSUE TITLE
请问,为什么限制不能打开.php的后缀?

### ISSUE THREAD

**Issue by pumpinger** [lincanbin/Carbon-Forum#204]
`
// 限制不能打开.php的网址
if (strpos($RequestURI, '.php')) {
	AlertMsg('404', '404 NOT FOUND', 404);
}
`
有什么好处呢

**Comment by lincanbin** [comment]
没啥，设置了Rewrite后，还允许.php的访问的话，一个页面会有多个访问路径，这样会降低这个页面在搜索引擎的权重。

**Comment by pumpinger** [comment]
是不是你这边部署了 .htaccess  ,代码索性也ban掉.php后缀,
如果我是nginx的话,就要懵逼2秒钟.
: )

**Comment by lincanbin** [comment]
Nginx也有Rewrite可以用啊。
