### ISSUE TITLE
when move to server, error:  Refused to display 'server url' in a frame because it set 'X-Frame-Options' to 'SAMEORIGIN'.

### ISSUE THREAD

**Issue by hoogw** [lincanbin/Carbon-Forum#205]
Hello Lin, 

    This is top one choice in the bbs market. It runs perfect on localhost, However,
when move to server, I got error: 
 Refused to display 'server url' in a frame because it set 'X-Frame-Options' to 'SAMEORIGIN'.   

I think when I move it from localhost to remote hosting server, 

I should config something like change localhost to server IP in somewhere, 

Please advise where I should do above config?

**Comment by hoogw** [comment]
If I use real IP, it works, for example:  http://192.63.25.1:10/carbon/   works fine

If I use domain name, it get above error for example:   http://bbs.mywebsite.com/  error above.

domain name "bbs.mywebsite.com" set forward to "http://192.63.25.1:10/carbon/"

**Comment by hoogw** [comment]
I found a solution.   Go to root folder, edit common.php file,

comment out 

//header('X-Frame-Options: SAMEORIGIN');

but I don't understand, why use this code?

**Comment by lincanbin** [comment]
Run `/update/index.php` when you move it from localhost to remote hosting server.
