### ISSUE TITLE
oauth

### ISSUE THREAD

**Issue by robotrono** [lincanbin/Carbon-Forum#211]
@lincanbin in you site I get Error 502 when Im trying to do login via github.

https://en.94cb.com/

**Comment by lincanbin** [comment]
![tim 20170412094402](https://cloud.githubusercontent.com/assets/5785188/24937624/9974f2ce-1f64-11e7-8cbc-b9f05508f2a4.png)

http://stackoverflow.com/questions/14193954/upstream-prematurely-closed-connection-while-reading-response-header-from-upstre

I seem to need to upgrade my PHP version.

**Comment by lincanbin** [comment]
Has been upgraded to the latest PHP 7.1.3.
