### ISSUE TITLE
user can edit their post? new feature?

### ISSUE THREAD

**Issue by hoogw** [lincanbin/Carbon-Forum#218]
Very good product, easy to use. 
Only 1 thing, if user can edit their post. 

Now, only admin can edit any post. which is good. 

but user can not edit their post, only can edit tags.

like github(this page, this post) I can edit my post.  Stackoverflow can edit my post too. 

If you can add feature let user edit their post, that would be Great.

**Comment by lincanbin** [comment]
I will add it.

**Comment by hoogw** [comment]
user role = 4 can edit post. 
I can manually edit mysql database, set user role = 4.

role = 3 means what?  3 can' t edit.

**Comment by skywhat** [comment]
That's a great idea.

**Comment by hoogw** [comment]
I have test this new feature, perfect!  test passed. 

the only improvement is that, 

is that possible to let user edit not only their post, but also their reply under it. 

now user can NOT edit their reply. 

for example, I can edit my reply in github.

**Comment by hoogw** [comment]
That works great!!!!!

now common user(role=1) can edit their post AND their reply!
Perfect, exact like what you can do here(github) or stackoverflow.

Should I close it? This new feature is WELL DONE.
