### ISSUE TITLE
how to switch language to English?

### ISSUE THREAD

**Issue by hoogw** [lincanbin/Carbon-Forum#221]
I download developer package, but it is in chinese. 

I want to switch to english, don't know how.

Do you have some idea?

**Comment by lincanbin** [comment]
![tim 20170526002427](https://cloud.githubusercontent.com/assets/5785188/26459697/e81e6196-41a9-11e7-8979-981c8ded3b16.png)

```php
define('ForumLanguage', 'en');
```

**Comment by lincanbin** [comment]
Or run `/update`.

**Comment by hoogw** [comment]
thank you very much. 
That works great. 

I close this issue.  
Let other people who has same question, can search 'switch language' to see this post.

Very useful tips.
