### ISSUE TITLE
Is it possible to make a dot net version?

### ISSUE THREAD

**Issue by hoogw** [lincanbin/Carbon-Forum#225]
This is a great software, like wordpress, it is a platform, 

literally you can add million things on this platform. 

Do you have a plan to make a dot net verion?

If you want to make dot net version, I will just sit and wait. 

If you do not want to make a .net version,  I think I can try it.  
I can use spare time. 

I believe this software can make money if customize it to specific need for specific people. 
1144 stars already approve it. 

keep developing.

**Comment by lincanbin** [comment]
I do not have time to do this.

**Comment by hoogw** [comment]
Ok, I see
