### ISSUE TITLE
如何更改语言设置？

### ISSUE THREAD

**Issue by haohaostudio** [lincanbin/Carbon-Forum#239]
我想把一件部署后的Carbon forum设置为中文，
但是真的不能在设置里面找到

**Comment by lincanbin** [comment]
基本不会修改的东西，是没有加进设置里的。
如果需要修改，有两种方法：
### 方法一：打开config.php，找到对应行，改为：
```php
define('ForumLanguage', 'zh-cn');
```
即可。

### 方法二：重新运行```/update```升级程序，选中中文保存即可。
