### ISSUE TITLE
sitemap 目录在哪里？

### ISSUE THREAD

**Issue by jjj107** [lincanbin/Carbon-Forum#241]
sitemap 目录在哪里？自动生成？还是手动。生成后的sitemap地图网址是多少？谢谢。

**Comment by lincanbin** [comment]
https://www.94cb.com/robots.txt

**Comment by jjj107** [comment]
谢谢，sitemap已经解决。但是又出现了一个问题，发表了一篇图文的文章查看文章的时候出现文字完全乱码。删了一次，有从新发还是这样乱码。我是自己在GitHub 上下载的 master 的压缩包。求解决。
[www.human-like.net/t/2](url)

**Comment by lincanbin** [comment]
数据库字符集不对？

**Comment by jjj107** [comment]
如果是字符集不对的话，网站标题应该也是乱码把。我看看数据库字符集

**Comment by jjj107** [comment]
是使用utf8 还是GB

**Comment by lincanbin** [comment]
utf-8

**Comment by jjj107** [comment]
set 完数据库后 用 show 查看数据库 

仍然是这样的  character_set_database | gbk

是不是因为买的空间原因不能更改成 utf8?

**Comment by lincanbin** [comment]
可能是，你联系下服务商吧。
post表里的也是乱码吗？

**Comment by jjj107** [comment]
数据库改好了，还是乱码。

**Comment by lincanbin** [comment]
新创建的也是乱码？

**Comment by jjj107** [comment]
是的，我把论坛重新建了还是乱码

**Comment by jjj107** [comment]
我的数据库字符集是这样设置的，你看下有没有问题。

1 | character_set_client | utf8
-- | -- | --
2 | character_set_connection | utf8
3 | character_set_database | utf8
4 | character_set_filesystem | binary
5 | character_set_results | utf8
6 | character_set_server | utf8
7 | character_set_system | utf8
8 | character_sets_dir | /usr/local/mysql/share/mysql/charsets/

**Comment by jjj107** [comment]
我发现一个问题就是，我把数据库的字符集调整好后，重新安装网站就会出现字符集变成gbk了。

**Comment by lincanbin** [comment]
这种情况你应该联系服务商解决了。
