### ISSUE TITLE
How to make forum private?

### ISSUE THREAD

**Issue by Tertuliano** [lincanbin/Carbon-Forum#247]
Hi, is there a way to put the forum private? For example, add a blank page only with the login to enter the forum?

Thanks...

**Comment by lincanbin** [comment]
Add this code to `controller/home.php` and  `controller/topic.php`
```php
Auth(1, 0, true);
```
![tim 20180308141802](https://user-images.githubusercontent.com/5785188/37136207-8d6d23c2-22db-11e8-83d3-1c609b820176.png)

![tim 20180308141918](https://user-images.githubusercontent.com/5785188/37136247-b931b8f6-22db-11e8-924c-c463a1d8b6c5.png)
