### ISSUE TITLE
请求更新编辑器或提供编辑器更新方法

### ISSUE THREAD

**Issue by 740291272** [lincanbin/Carbon-Forum#260]
请求更新编辑器或提供编辑器更新方法
找了好长时间，都更换失败了

**Comment by 740291272** [comment]
只更换editer内js无法正常使用

**Comment by 740291272** [comment]
貌似与其他js有关系

**Comment by lincanbin** [comment]
那肯定啊……
我看你应该没怎么写过前端。
editer内的js是lib，其他地方还有各种call的。

**Comment by 740291272** [comment]
那其他地方引用怎么替换？

**Comment by lincanbin** [comment]
所有调用到editor的地方都根据你新的editor里的调用规则重写。

**Comment by 740291272** [comment]
恩，我看看

**Comment by 740291272** [comment]
那会考虑更新uediter吗

**Comment by lincanbin** [comment]
暂时没找到功能更全的。

**Comment by 740291272** [comment]
就是更新版本，因为这个老版本uediter编辑器不能内嵌页面，比较麻烦，新版本可以自定义白名单。

**Comment by lincanbin** [comment]
我这个已经是最新的UEditor了吧。

**Comment by lincanbin** [comment]
难道UEditor又更新了？我去看看。

**Comment by 740291272** [comment]
最新版的可以设置输入白名单

**Comment by lincanbin** [comment]
https://github.com/fex-team/ueditor/releases
上次release还是2年前好吗？

**Comment by 740291272** [comment]
我要使用iframe，这个对我的站很重要，但是这个版本没有白名单，不能设置。

**Comment by 740291272** [comment]
或者是被关了？

**Comment by lincanbin** [comment]
common.php里搜$hostWhiteList，那个是白名单，iframe你可以直接用代码插入。
插入iframe的功能默认关了，你在UEditor官网可以找到插入方法。

**Comment by 740291272** [comment]
哦哦哦，谢谢
