### ISSUE TITLE
发帖，link 的 URL中如果有 “&” 就会失败

### ISSUE THREAD

**Issue by hoogw** [lincanbin/Carbon-Forum#262]
比如说：
我想发一个link，URL如下，含有 ‘&’
http://googlemaps/parcels-la/parcels?api=1&layer_id=333

当我保存的时候，在数据库看到href=""，为空，这是为什么？

a href="" target="_blank" title="tt"

**Comment by lincanbin** [comment]
https://github.com/lincanbin/White-HTML-Filter/issues/1

前几天有人反馈了。

https://github.com/lincanbin/Carbon-Forum/commit/beb0bbc8ae780e1c6d9d779fa094c85787f424d2
替换这个文件为新版即可。
