### ISSUE TITLE
数据库名称没有过滤，存在安全风险

### ISSUE THREAD

**Issue by nabice** [lincanbin/Carbon-Forum#265]
https://github.com/lincanbin/Carbon-Forum/blob/793ceca80cade95b1aeca5675cb944e79fb62e71/install/index.php#L53

我觉得最好还是稳妥一点，把这里改成参数化处理。

**Comment by nabice** [comment]
虽然设置了PDO::ATTR_EMULATE_PREPARES， 但风险依然存在是吧。

**Comment by lincanbin** [comment]
没有必要，安装程序只有拥有服务器权限和数据库权限的管理员才有权限跑。
谁会自己黑自己？
