### ISSUE TITLE
我的数据库 carbon_dict 里面为什么总是为空？导致搜索提示功能，失败

### ISSUE THREAD

**Issue by hoogw** [lincanbin/Carbon-Forum#267]
我的数据库 carbon_dict 里面为什么总是为空？

导致搜索提示功能，失败， 总是空的。
tag提示功能，失败， 总是空的。

json.php 文件里面，tag_autocomplete， 

PHPAnalysis.class.php 
里面 LoadDict() //载入词典 功能似乎是失败的。

请问： 数据库 carbon_dict 是如果填充数据的？
是不是每个新的tag，都加到词典里？
每个帖子标题拆成单个词，加到词典里？

在什么地方设置，加词？
我这里词典永远是空的，一个词也没有。

**Comment by hoogw** [comment]
我自己改了一下，挺好用的，有同样问题的朋友可以试试，
改这个文件  controller\json.php

干脆不用 dict table 
直接搜索 tags table

               `case “tag_autocomplete”:
                 。。。。。
                  。。。。
                   。。。
               
                $Result            = $DB->column("SELECT Name FROM " . PREFIX . "tags WHERE Name LIKE :Keyword limit 10", array(
			"Keyword" => $Keyword . "%"
		));`


另外再加一个 case, 这个是主页顶上搜 帖子 标题的，大搜索。

         `   case 'searchTopic_autocomplete':

		..........

               .....................

                $Result            = $DB->column("SELECT Topic FROM " . PREFIX . "topics WHERE Topic LIKE :Keyword limit 10", array(
			"Keyword" => "%". $Keyword . "%"
		));`
            



另外一个改动， 原来的tag_autocomplete 改成 searchTopic_autocomplete
static\js\default\global.js

              `$("#SearchInput").autocomplete({
		//serviceUrl: WebsitePath + '/json/tag_autocomplete',
             
                serviceUrl: WebsitePath + '/json/searchTopic_autocomplete',`


这个地方不用改，知道就好。这里是tag 联想提示用的。
static\js\default\new.function.js

`$("#AlternativeTag").autocomplete({
		serviceUrl: WebsitePath + '/json/tag_autocomplete',`

**Comment by lincanbin** [comment]
https://www.94cb.com/t/2199
