### ISSUE TITLE
如何修改数据库实现用户名强制大写

### ISSUE THREAD

**Issue by ghost** [lincanbin/Carbon-Forum#269]
如题，如何修改数据库以实现用户名强制大写？

**Comment by lincanbin** [comment]
去掉register控制器里的strtolower函数

**Comment by t-hua** [comment]
好的。

**Comment by ghost** [comment]
// $UserLanguages = array_combine($LangParse[1], $LangParse[4]);
												foreach ($LangParse[1] as $Key => $Value) {
													$UserLanguages[strtolower($LangParse[1][$Key])] = $LangParse[4][$Key];
												}
是这一条嘛？

**Comment by lincanbin** [comment]
是register控制器里的

**Comment by ghost** [comment]
我是想在安装之前直接在源码里改，如何操作？

**Comment by lincanbin** [comment]
register控制器里的
```php
$UserName   = strtolower(Request('Post', 'UserName'));
```
改成strtoupper
