### ISSUE TITLE
加密算法的盐值是多少

### ISSUE THREAD

**Issue by ghost** [lincanbin/Carbon-Forum#274]
密码忘记了，邮箱没设置。。。
盐值是多少？
或者麻烦给出123456加密后的结果。

**Comment by lincanbin** [comment]
是数据库中对应用户的Salt字段，每个用户的盐值都不一样。

**Comment by lincanbin** [comment]
https://www.94cb.com/t/2584-1#Post14370

**Comment by ghost** [comment]
好吧，我的阿里虚机里面数据库没有盐值数值。。
