### ISSUE TITLE
官网6.0验证码大小问题

### ISSUE THREAD

**Issue by ghost** [lincanbin/Carbon-Forum#276]
官网6.0过大了。。。影响体验。。。麻烦开发者换回5.9的验证码或者稍微调小一点。

**Comment by lincanbin** [comment]
大了看得清啊。

**Comment by ghost** [comment]
个人认为。。。稍微小一点也是可以的，太大了体验不好。其实5.9的已经可以了，在5.9基础上大一点就行了。

**Comment by lincanbin** [comment]
5.9强度不够，不够安全。
提高强度后需要调大才能方便识别。

**Comment by ghost** [comment]
好吧。
