### ISSUE TITLE
How to change Carbon Forum in header

### ISSUE THREAD

**Issue by metalsunny** [lincanbin/Carbon-Forum#291]
Hello,
I like carbon forum so much but I don't know how to change thr header titilevfrom carbon forum to the name of my forum.
Help pls

**Comment by lincanbin** [comment]
![image](https://user-images.githubusercontent.com/5785188/48253008-36e84900-e441-11e8-910c-f2f069d3c449.png)

**Comment by metalsunny** [comment]
Thank you. It worked...
