### ISSUE TITLE
安装后注册用户显示： You don't have permission to access /cb/register on this server.

### ISSUE THREAD

**Issue by Sender-cheng** [lincanbin/Carbon-Forum#302]
项目文件夹是cb，安装好后想注册第一个用户，结果提示 ： You don't have permission to access /cb/register on this server.

**Comment by lincanbin** [comment]
你的Apache权限设置有问题吧？

**Comment by lincanbin** [comment]
Google搜索这个错误，有解决方案

**Comment by Sender-cheng** [comment]
好吧，好像是phpstudy的“网站域名管理”设置有误。
![gan_ga](https://user-images.githubusercontent.com/18100743/55284415-b9e64d80-53a8-11e9-972b-e1423290f1ca.jpg)
