### ISSUE TITLE
安装后除了首页其他都404

### ISSUE THREAD

**Issue by wwwAngHua** [lincanbin/Carbon-Forum#321]
我使用的nginx作为web服务器，php版本为7.4，mysql为5.7，应该需要配置伪静态等内容，但文档没有描述，求解决。

**Comment by wwwAngHua** [comment]
nginx.conf配置到nginx的伪静态已得到解决

**Comment by alitheDev** [comment]
太好了，你已经解决了这个错误，你能分享更多关于你如何解决这个问题的细节吗？谢谢
