### ISSUE TITLE
 Carbon-Forum/includes/dict/words_addons.dic

### ISSUE THREAD

**Issue by LNDDYL** [lincanbin/Carbon-Forum#49]
https://github.com/lincanbin/Carbon-Forum/blob/master/includes/dict/words_addons.dic
這是什麼東西，需要翻譯嗎？

**Comment by LNDDYL** [comment]
https://github.com/lincanbin/Carbon-Forum/blob/master/static/editor/dialogs/template/config.js
它需要翻譯，網址先貼到這（就當作這裡是網頁書籤收藏庫了）。

**Comment by lincanbin** [comment]
没有放到Language文件夹里的都是暂时不需要翻译的（为预留功能，实际上并未在程序中出现，未来也不一定出现）

**Comment by LNDDYL** [comment]
![_2015-05-08t05-39-46 567z](https://cloud.githubusercontent.com/assets/4318463/7531192/6f663ea0-f588-11e4-84c9-48bc326d2097.png)
這些中文譯了麼？

**Comment by lincanbin** [comment]
已经翻译

**Comment by LNDDYL** [comment]
![_2015-05-08t05-44-38 054z](https://cloud.githubusercontent.com/assets/4318463/7531239/11a82f0c-f589-11e4-9c36-bde69cc8d42b.png)
英文站沒有「站內統計」功能，是版本沒更新的緣故？

**Comment by lincanbin** [comment]
http://en.94cb.com/
有的

**Comment by LNDDYL** [comment]
喔，原來是這樣：404頁面沒有「站內統計」 http://en.94cb.com/t/55555

**Comment by LNDDYL** [comment]
英文站的search功能有Bug：404頁面不存在 http://en.94cb.com/search/1

**Comment by lincanbin** [comment]
查无结果即为404，同时登陆后可检索的范围会更大。

**Comment by LNDDYL** [comment]
404 Not Found有一種網頁不存在的感覺，有點不夠人性化。搜不到內容應該提示「查無結果」之類的話。

**Comment by LNDDYL** [comment]
404頁面沒有「站內統計」功能 http://en.94cb.com/t/55555

**Comment by lincanbin** [comment]
下午回来一并订正。

**Comment by LNDDYL** [comment]
「網頁不存在」與「搜不到內容」是兩回事。

**Comment by LNDDYL** [comment]
大概半小時前吧，我又做了一個安裝頁的翻譯，請求通過。

**Comment by lincanbin** [comment]
安装页部分加上繁体中文后，每行的宽度都已经超过了设定的值，页面已经完全变形了。
所以没办法通过了。
只能以后再分离出多种语言再行翻译。

**Comment by LNDDYL** [comment]
呃，好吧…………
