### ISSUE TITLE
台灣站

### ISSUE THREAD

**Issue by LNDDYL** [lincanbin/Carbon-Forum#51]
http://tw.94cb.com/
我現在就註冊，請給我管理員權限。多謝！

**Comment by LNDDYL** [comment]
http://tw.94cb.com/t/1
這個貼文（post，簡中：帖子）需要修改呀！詞彙不符合台灣的語言習慣。

**Comment by LNDDYL** [comment]
zh-tw就是中文（台灣）

**Comment by LNDDYL** [comment]
likehot是我

**Comment by lincanbin** [comment]
好了，你现在应该可以编辑、删除任何帖子与封禁任何用户了。

**Comment by LNDDYL** [comment]
訊息列在哪改？

**Comment by lincanbin** [comment]
官网在数据库锁定了后台设定，无法从网页上修改。

**Comment by LNDDYL** [comment]
解開吧，那裡也要改的。

**Comment by LNDDYL** [comment]
我修改的翻譯會同步到網站（http://tw.94cb.com）中嗎？

**Comment by lincanbin** [comment]
不会，同步程序需要花费很多时间。
所以一般是十几天同步一次。

**Comment by LNDDYL** [comment]
submit不了

**Comment by LNDDYL** [comment]
沒找到發佈新貼文的位置

**Comment by LNDDYL** [comment]
下載地址 改為 下載網址

**Comment by LNDDYL** [comment]
「未選擇檔案」這句字串在哪裡？找不到。

**Comment by LNDDYL** [comment]
行動版的搜尋功能有Bug，在未登入帳號的情況下，搜尋任何字都是404 Not Found，登入後正常。

**Comment by LNDDYL** [comment]
這兩句沒翻譯。
![_2015-05-08t12-50-41 824z](https://cloud.githubusercontent.com/assets/4318463/7536719/c16934aa-f5c4-11e4-885a-8d29fa67e626.png)
![2](https://cloud.githubusercontent.com/assets/4318463/7536720/c16dd51e-f5c4-11e4-94a6-a7df541fbd61.png)

**Comment by LNDDYL** [comment]
![20150509_092606](https://cloud.githubusercontent.com/assets/4318463/7548055/97b2de7c-f62d-11e4-99b8-e082e22b24fe.jpg)
這是「訊息列」（message bar）？不對吧？

**Comment by lincanbin** [comment]
行动模式的预留栏目

**Comment by LNDDYL** [comment]
這是譯錯了，Information bar是資訊列（informationbar也不對呀，應該是menu bar才對）。

另外，目前行動版的「訊息列」跟桌面版的「訊息列」是同一個嗎？

**Comment by LNDDYL** [comment]
應該再加入一個在帳號設定(account settings)裡更改預設時區（default time zone）的功能，因為所有人都在東八區。

**Comment by LNDDYL** [comment]
使用者名稱(user name)區分簡繁體嗎？

**Comment by lincanbin** [comment]
是同一个，并且时区对于这个程序意义不大。
大部分时候，时间都是显示**小时之前或者**天之前——这个并不受时区约束。
使用者名称是区分简体和繁体的。

**Comment by LNDDYL** [comment]
靠！少寫一個字……我是說，不是所有人都在東八區。

**Comment by lincanbin** [comment]
我的意思是：时区的功能在程序中并没有任何体现……
程序不直接显示日期，而是显示*天前——这点与时区无关。
写时区只是我的习惯而已，实际上并没有显著作用。

**Comment by LNDDYL** [comment]
關於上面的A問題與B問題，你需要解決一下。另外，下圖的「確定」位於何處？
![_2015-05-09t11-30-16 316z](https://cloud.githubusercontent.com/assets/4318463/7550005/8dddd8ac-f682-11e4-82fa-8afe904c9fdd.png)

**Comment by lincanbin** [comment]
zh-tw.js

**Comment by LNDDYL** [comment]
OK，那……你趕快通過我的合併請求，方便我的下一步修改。

**Comment by LNDDYL** [comment]
那些沒翻譯的地方，你……？

**Comment by LNDDYL** [comment]
我開啟了檢視原始碼（view source code）功能，發現了這句話，此句位於何處？
![default](https://cloud.githubusercontent.com/assets/4318463/7550136/b345178a-f688-11e4-8505-2ef57869c939.png)

**Comment by LNDDYL** [comment]
呀！圖片沒有繁化。
https://github.com/lincanbin/Carbon-Forum/tree/master/language/zh-tw/images

**Comment by lincanbin** [comment]
原始码中的这句话位于数据库中，是管理员设定的，无需繁化。
然后你能不能把多次修改合并为一个commit，不然的话，这几天这么多的pull request会导致很多冲突，让我这边的开发工作都已经完全终止，无法进行了。

我让我的一些澳门和香港的同学看了，繁体版现在看起来是没有任何理解上的偏差了，应该暂时告一段落，然后我也可以继续我的开发工作了。

然后图片同样无需繁化，因为图片出现的场景非常少见，有些甚至从未出现。

**Comment by LNDDYL** [comment]
插入音樂那個出現了（百度音樂）

**Comment by LNDDYL** [comment]
「不能把多次修改合并为一个commit」
關於這個……我對GitHub不太熟悉，我再學習學習，抱歉……

**Comment by LNDDYL** [comment]
翻譯，我就差一個了，把zh-tw.js中的「確定」改成「確認」。
以下三處：
![_2015-05-09t12-29-58 698z](https://cloud.githubusercontent.com/assets/4318463/7550213/89eb884e-f68b-11e4-87d8-d72ca86bc2c6.png)
![_2015-05-09t12-30-21 138z](https://cloud.githubusercontent.com/assets/4318463/7550214/89eeff1a-f68b-11e4-962e-70800a4469c6.png)

「精確定位」不算啊。
修改成「確認」是為了翻譯風格的統一。

**Comment by LNDDYL** [comment]
![_2015-05-09t12-41-58 650z](https://cloud.githubusercontent.com/assets/4318463/7550236/83a67cea-f68c-11e4-8d49-360a7b6193c6.png)
這裡不應該叫作Information Bar，Menu Bar才是正確的，這裡應該與Information Bar拆分開。

**Comment by lincanbin** [comment]
这个本来是预留来给管理员随便放点东西的。
想了想我觉得之后把Information Bar这个直接给删了，就没这事了。

**Comment by LNDDYL** [comment]
我突然想起一個問題，Carbon Forum有block（封鎖，停權）人的功能。假如某人被block，我能否看到他被block的提示。

**Comment by LNDDYL** [comment]
你有考慮「使用者名稱黑名單」(user name  blacklist)功能嗎？禁止使用某個特定的使用者名稱。

**Comment by lincanbin** [comment]
只有被block的用户才可以看见被block的提示。
使用者名称黑名单有考虑加入。

**Comment by LNDDYL** [comment]
某個帳號被block，我也不知道啊，會讓人產生一個疑問：「為什麼那個帳號不說話？為什麼？為什麼？」

**Comment by LNDDYL** [comment]
![_2015-05-09t12-41-58 650z](https://cloud.githubusercontent.com/assets/4318463/7550346/03b1a618-f691-11e4-8faa-23ab9fb1811f.png)
這是維基百科的截圖，帳號有更改系統語言的功能（只對自己的帳號有效）。這，你有考慮嗎？

**Comment by lincanbin** [comment]
暂无

**Comment by LNDDYL** [comment]
什麼「暫無」？

**Comment by LNDDYL** [comment]
某個帳號被block，我也不知道啊，會讓人產生一個疑問：「為什麼那個帳號不說話？為什麼？為什麼？」
至少應該給個被block的提示，給個不說話的理由吧？

關於這個，你……？

**Comment by lincanbin** [comment]
就是暂无考虑。
那我到时再给被block的用户加个标识——但我一直觉得这样有种给被block用户套上囚服的感觉。

**Comment by LNDDYL** [comment]
可以加一個對特定人（比如說已註冊的使用者）開放瀏覽論壇的功能嗎？往論壇里私密內容時特別有用。

**Comment by LNDDYL** [comment]
據我所知，Discuz!有這一功能。

**Comment by lincanbin** [comment]
这个只需要加入一行代码即可实现。
http://www.94cb.com/t/2277
但是并未打算加入。

**Comment by LNDDYL** [comment]
關於A的問題（https://github.com/lincanbin/Carbon-Forum/issues/51#issuecomment-100224937），你一直沒有答覆我。

**Comment by LNDDYL** [comment]
在個人頁面（比如http://www.94cb.com/u/admin ）顯示UserLastIP，該如何實現？

**Comment by LNDDYL** [comment]
![default](https://cloud.githubusercontent.com/assets/4318463/7554050/6e146082-f749-11e4-8235-92cadc239d59.PNG)
點刪除出現了這樣一個問題

**Comment by LNDDYL** [comment]
![default](https://cloud.githubusercontent.com/assets/4318463/7554188/fb34a010-f750-11e4-91bc-d3b534c5cb39.PNG)

**Comment by lincanbin** [comment]
剩下少部分操作的语言包尚未提取，日后一并完成。
需要显示最后登陆IP，可以在styles/default/template/user.php对应位置加入
```php
<?php echo $UserInfo['UserLastIP']; ?>
```

**Comment by LNDDYL** [comment]
你只需把Confirm_Operation的代碼及位置告訴我，我自己加中文。

**Comment by lincanbin** [comment]
https://github.com/lincanbin/Carbon-Forum/blob/master/static/js/global.js#L87

**Comment by LNDDYL** [comment]
對公眾公開IP是不安全的行為。
只對管理員公開，應該加入什麼代碼？

**Comment by LNDDYL** [comment]
Confirm_Operation的翻譯應該寫在哪裡？

**Comment by lincanbin** [comment]
目前Confirm_Operation还没有提取出来，如果你需要的话只能直接写在global.js里了
var Lang = {Confirm_Operation : '确认'};
···php
<?php
if($CurUserRole>=4){
    echo $UserInfo['UserLastIP'];
}
?>
···
上面这样可以实现只有管理员可以查看IP。

**Comment by LNDDYL** [comment]
4代表管理員？其他數字呢？

**Comment by LNDDYL** [comment]
關於A的問題（https://github.com/lincanbin/Carbon-Forum/issues/51#issuecomment-100224937 ），你一直沒有答覆我。

**Comment by LNDDYL** [comment]
被block帳號的標示，利用類似於上面的UserLastIP代碼也可以實現吧？我會舉一反三了喔！哈哈！

**Comment by lincanbin** [comment]
CurUserRole = 1是普通会员，其他数字是留着备用的。

这是被Block账号的标识。
```php
<?php
if(!$UserInfo['UserAccountStatus']){
    echo '当前用户已被封禁';
}
?>
```

**Comment by LNDDYL** [comment]
不是說還有VIP、版主之類的嗎？話說，關於A問題，你仍未答覆我……

**Comment by lincanbin** [comment]
A问题就是——这部分的翻译我也还没有调整出来，因为下个版本行动模式要大改。

**Comment by LNDDYL** [comment]
找回密碼的功能一定要加啊！

**Comment by lincanbin** [comment]
是

**Comment by LNDDYL** [comment]
方便提前透露「找回密碼」的代碼嗎？

**Comment by lincanbin** [comment]
这部分我还没写。

**Comment by LNDDYL** [comment]
如何做，使用者名稱才能不區分簡繁體？

**Comment by LNDDYL** [comment]
VIP成員、版主、超級版主、管理員，怎樣把這些User group授與其他帳號？

**Comment by LNDDYL** [comment]
![_2015-05-11t07-12-27 574z](https://cloud.githubusercontent.com/assets/4318463/7560080/0c072650-f7f2-11e4-8c62-2ced272ea547.png)
這裡為何出現簡體字？

**Comment by lincanbin** [comment]
这部分只是数据库标识，实际上并没有任何作用。
修改用户权限将在之后版本加入。
简繁本来就不是同一个字，因而不可能不区分。

**Comment by LNDDYL** [comment]
封IP功能有考慮加入嗎？

**Comment by LNDDYL** [comment]
我再問一下關於.htaccess的問題，我想把http://a.b.com （包含下級路徑）轉到https://a.b.com （包含下級路徑），該怎麼寫？

**Comment by LNDDYL** [comment]
說明白點，就是：把http非加密頁面跳轉至https加密頁面，該怎麼做？

**Comment by LNDDYL** [comment]
![_2015-05-12t06-27-09 248z](https://cloud.githubusercontent.com/assets/4318463/7581474/146de710-f8b6-11e4-988e-11418130e40d.png)
加什麼代碼才能有連結（link，簡中：链接），連結到個人主頁？像Facebook、Google+、Twitter、微博之類都是有連結的。

**Comment by LNDDYL** [comment]
![_2015-05-12t10-05-07 667z](https://cloud.githubusercontent.com/assets/4318463/7584728/0eba1f20-f8d2-11e4-9ff8-ff1512e70524.png)
怎麼顯示發佈者的IP(PostIP)？
![_2015-05-12t10-08-24 548z](https://cloud.githubusercontent.com/assets/4318463/7584815/cf8fc3c6-f8d2-11e4-9d13-75180ad4b188.png)

**Comment by LNDDYL** [comment]
我在/styles/default/template/topic.php中加了以下代碼，但是無效。
<?php
if($CurUserRole>=4){
    echo ' [IP：';
    echo $post['PostIP'];
    echo ']';
}
?>

**Comment by LNDDYL** [comment]
有什麼錯誤嗎？
是 echo $Post['PostIP']; ？
還是 echo $Topic['PostIP']; ？
還是 echo $UserInfo['PostIP']; ？

**Comment by lincanbin** [comment]
暂无此类功能，待规划。

**Comment by LNDDYL** [comment]
顯示發佈者IP呢？

**Comment by LNDDYL** [comment]
「暂无此类功能」，什麼功能？

**Comment by LNDDYL** [comment]
發佈之後無法再修改標籤

**Comment by LNDDYL** [comment]
人呢？

**Comment by LNDDYL** [comment]
怎麼新增一組emotion？

**Comment by lincanbin** [comment]
会编程的一看就知道怎么处理，不会的我也很难说明白。
只能说，目前没有以上所有这些功能。
有的是不打算加，有的是有打算还没加。

**Comment by ShikiSuen** [comment]
@lincanbin 不妨將目前「停權」的英文「block」改成「ban」。block 趨向於社區內兩個會員之間出於拒絕通信而設立的功能，這在 Facebook 目前稱作「封鎖」；而「停權」則是站方管理團隊將特定帳號的會權權限叫停。
