### ISSUE TITLE
Web Page Reconstruction with CSS

### ISSUE THREAD

**Issue by lincanbin** [lincanbin/Carbon-Forum#6]

**Comment by lincanbin** [comment]
![174001_hwtu_1413782](https://cloud.githubusercontent.com/assets/5785188/6267288/a1a67be8-b87d-11e4-88f3-8348e39002ab.png)
![174025_prre_1413782](https://cloud.githubusercontent.com/assets/5785188/6267289/a1ac6210-b87d-11e4-9a10-fc11f56a4bc6.png)
![174039_y60w_1413782](https://cloud.githubusercontent.com/assets/5785188/6267292/a1b1a82e-b87d-11e4-9c58-404275734d88.png)
![174114_5zsr_1413782](https://cloud.githubusercontent.com/assets/5785188/6267291/a1b10978-b87d-11e4-9031-6c723aa2aa82.png)
![174314_tvwm_1413782](https://cloud.githubusercontent.com/assets/5785188/6267290/a1af22b6-b87d-11e4-8752-67aec865876b.png)

**Comment by axisdos** [comment]
The design isn't at its finest yet. You can take some inspirations from the Misago Project. I think they have the best layout An example: http://misago-project.org/thread/january-update-400/
