### ISSUE TITLE
如何适应手机版

### ISSUE THREAD

**Issue by toeasy** [lincanbin/Carbon-Forum#64]
请问手机版http://en-m.94cb.com/ 效果如何设置？

**Comment by lincanbin** [comment]
http://www.94cb.com/t/2529

**Comment by toeasy** [comment]
看了你写的说明 ，还是有疑问：如果我在本地localhost部署，如何写二级域名。另外二级域名不适应所有的情况，比如一些场景使用http//host/bbs这样访问。能否自适应手机移动浏览器?

**Comment by lincanbin** [comment]
本地部署的话，我是这样测试的：
给PC版分配一个127.0.0.1的主机名，给移动版分配一个localhost的主机名。

然后是二级目录，二级目录同样可以绑定并自动跳转到手机版http//m.host/bbs，这点我已经考虑了。
