### ISSUE TITLE
includes/logs/ folder has security  issue

### ISSUE THREAD

**Issue by baojie** [lincanbin/Carbon-Forum#70]
this is a publicly accessible folder, and contains database logs. Log should be written to a non-public folder, or this folder should be protected

**Comment by lincanbin** [comment]
https://github.com/lincanbin/Carbon-Forum/blob/master/.htaccess#L14

Remove the comment character.

```
	RewriteRule ^includes - [F,L]
	RewriteRule ^language - [F,L]
	RewriteRule ^styles/default/template - [F,L]
	RewriteRule ^styles/mobile/template - [F,L]
	RewriteRule ^styles/api/template - [F,L]
```

**Comment by baojie** [comment]
Ya. this works. Thanks.
