### ISSUE TITLE
安装完后打开页面 “Fatal Error !”

### ISSUE THREAD

**Issue by Jarvanh** [lincanbin/Carbon-Forum#72]
![2](https://cloud.githubusercontent.com/assets/5900885/7682591/b636d526-fdab-11e4-8d23-c825f429f25b.jpg)

无法打开页面

![3](https://cloud.githubusercontent.com/assets/5900885/7682600/c22ab3de-fdab-11e4-89f7-93439b91770a.jpg)

**Comment by lincanbin** [comment]
删除upload目录下的.htaccess文件试试？（如果有这个文件的话）
你的是Windows主机？

**Comment by Jarvanh** [comment]
删除upload目录下的.htaccess文件和根目录下的.htaccess文件都不行

linux来的

![4](https://cloud.githubusercontent.com/assets/5900885/7683022/d78ca09a-fdae-11e4-8b20-7ec301e6a4bf.jpg)

**Comment by lincanbin** [comment]
哦，是nginx。
我安装说明里应该有说，nginx要复制程序根目录的nginx.conf里的rewrite配置到vhost下对应的配置文件里。

**Comment by lincanbin** [comment]
哦，是nginx。
我安装说明里应该有说，nginx要复制程序根目录的nginx.conf里的rewrite配置到vhost下对应的配置文件里。

**Comment by Jarvanh** [comment]
有的，我配置了。

**Comment by lincanbin** [comment]
你看下详细错误日志吧

**Comment by lincanbin** [comment]
好了，我猜你使用SFTP直接传的文件？
这样的话，你的文件owner应该是root？这样的话Nginx是无法读取文件的，你或许应该尝试把所有文件的owner改为www（总之就是改为Nginx的用户），然后再全部设置777权限。

**Comment by Jarvanh** [comment]
我直接git clone的

chmod -R 777 Carbon-Forum后解决
