### ISSUE TITLE
微信、QQ登录

### ISSUE THREAD

**Issue by sdcsyyg** [lincanbin/Carbon-Forum#78]
请问有微信、QQ登录的开发安排吗？

**Comment by lincanbin** [comment]
有

**Comment by sdcsyyg** [comment]
@lincanbin 好的，谢谢，是最近在开发吗？

**Comment by lincanbin** [comment]
![img](https://cloud.githubusercontent.com/assets/5785188/7678142/4f96e512-fd84-11e4-8225-83020e8f3688.png)

最近在做的是[Carbon Forum的安卓客户端](https://github.com/lincanbin/Android-Carbon-Forum)，等做差不多就跳回去做服务端的开发了，下个版本的Carbon Forum升级估计会有加入Oauth的相关功能。

**Comment by sdcsyyg** [comment]
@lincanbin  Thx
