### ISSUE TITLE
如果没打开Apache的header_module 会报500

### ISSUE THREAD

**Issue by RichardPh** [lincanbin/Carbon-Forum#82]
建议在README的Requirement部分增加 `need headers_module`

**Comment by lincanbin** [comment]
mod_headers是默认编译而且默认打开的吧。
如果关了肯定是编译时参数搞错了。

**Comment by RichardPh** [comment]
默认打开的么？我看了同事的几台电脑，没发现是默认打开的。

如果可以的话，还是建议把需要加载的模块都写进去。

**Comment by lincanbin** [comment]
已修改ReadMe
