### ISSUE TITLE
WP手机系统浏览器打开空白

### ISSUE THREAD

**Issue by codejam1024** [lincanbin/Carbon-Forum#83]
用WP的手机打开手机端页面会显示空白，手机：Lumia920，系统版本：WP8.1

**Comment by lincanbin** [comment]
下个版本将会进行完全的重构，届时这个问题将解决。

WP的IE问题挺多，我没有WP手机，并且我问遍了我的朋友也没找到一部WP手机，所以当时这个版本没有做WP兼容性测试，我看Windows IE11运行正常就没管了。

后来问了网友，确实在一部分WP手机上会出现这个问题，在另一部分则不会。

总之下个版本将会解决，适配WP IE11是像适配IE6那样的麻烦事。

**Comment by LNDDYL** [comment]
Browser Screenshots for Quick Testing - 300+ Real Browsers, Internet Explorer 6-10, Local Testing, API, Resolution Options.
https://www.browserstack.com/screenshots

**Comment by lincanbin** [comment]
@LNDDYL 感谢提供资源。

**Comment by LNDDYL** [comment]
呀！沒有Windows Phone，抱歉，沒幫上你，囧Orz...

**Comment by lincanbin** [comment]
已修复
