### ISSUE TITLE
Problem with login and register

### ISSUE THREAD

**Issue by Tehiro** [lincanbin/Carbon-Forum#9]
After installation, I can't register. I get the message 404 NOT FOUND.  I'm trying to go to localhost/register.php and localhost/register and does not work.

**Comment by lincanbin** [comment]
You need to ensure that the rewrite module is enabled. (The [__mod_rewrite__](http://httpd.apache.org/docs/2.2/mod/mod_rewrite.html) Apache module, [__ISAPI_Rewrite__](http://www.helicontech.com/isapi_rewrite/) IIS module or [nginx rewrite module](https://github.com/lincanbin/Carbon-Forum/blob/master/nginx.conf) )

**Comment by Tehiro** [comment]
Ahh... Yes... My bad. Sorry for the problem. I'm starting to test :)
