### ISSUE TITLE
[Bug 修复] 绑定 GitHub 账号后的显示有误

### ISSUE THREAD

**Issue by Geno1024** [lincanbin/Carbon-Forum#94]
绑定 GitHub 账号后，出现了以下的显示：
![default](https://cloud.githubusercontent.com/assets/6427392/9987984/59459406-607f-11e5-9c77-78190e186297.png)
“错误消息”，又“绑定成功”。。。
还没看清楚代码，不知道错误的由来，没法提供帮助，抱歉。

**Comment by lincanbin** [comment]
啊，这就是字写错了而已，实际上已经绑定成功，没有发生任何错误。
因为程序做了国际化支持，语言文件跟模板文件是完全分离的，等下我去改一下文字就行了。

**Comment by Geno1024** [comment]
嗯，我也在 GitHub 上看到了绑定了，并且在 language 文件夹中发现了 i18n，就感觉应该只是一个引用之类的问题吧。
顺便求师兄罩啊，这里 15 小鲜肉一枚～

**Comment by lincanbin** [comment]
我现在找不到工作，自身难保，我也罩不了你。

**Comment by Geno1024** [comment]
卧槽…抱歉…

**Comment by lincanbin** [comment]
没事，是我自己眼高手低。
