### ISSUE TITLE
使用 微博 登录后，未获取用户名

### ISSUE THREAD

**Issue by sinkcup** [lincanbin/Carbon-Forum#95]
使用 微博 登录后，未获取到我的微博用户名，仍然要手动输入。如图：

![2015-09-25 13 24 17](https://cloud.githubusercontent.com/assets/4971414/10093719/1c76f670-6389-11e5-850e-57f4d2537a33.png)

设置里显示Unknown，也许这是另一个bug？

![2015-09-25 13 24 54](https://cloud.githubusercontent.com/assets/4971414/10093724/204e1e9a-6389-11e5-85a9-8e6ecc43cf10.png)

**Comment by lincanbin** [comment]
![qq 20150925135018](https://cloud.githubusercontent.com/assets/5785188/10093951/635a93c8-638c-11e5-8dd1-fac6ee8c2631.png)
这当然不是一个bug。

这是因为官网服务器在国外，新浪表示无法访问，所以一直过不了审核。
实际上官网的微博登陆接口一直处于审核状态，因此是没有权限获取用户的微博ID的。

艹蛋的问题，我联系了新浪客服，但是没有任何回应。

**Comment by lincanbin** [comment]
https://www.94cb.com/t/2980#Post9861

已过审。
